# org: drpappa
# app: project-genesis
service: project-genesis

frameworkVersion: "2"

useDotenv: true

provider:
  name: aws

plugins:
  - serverless-finch

custom:
  client:
    bucketName: project-genesis-a-software-development-fantasy
    distributionFolder: ./build
    region: eu-west-1
